### ISSUE TITLE
Incomplete Files

### ISSUE THREAD

**Issue by tbartlett17** [RemixDev/DRemixIssues#158]
#### Issue description
When I download an album, some files are partially and not fully downloaded.

#### Steps to reproduce the issue

1.  Search for an artist
2.  View all albums by artist
3.  Click the download album button

#### What's the expected result?

-Album is fully downloaded, all files are intact and complete. 

#### What's the actual result?

-Some files are not fully downloaded. Playback of songs is halted early, file sizes are not correct for what they should be.

#### Screenshot
![image](https://user-images.githubusercontent.com/36083073/73588754-be283f00-4481-11ea-9fb8-b306333a2e5d.png)

#### Desktop: 
- OS: Windows 10 Education
- Version 1809

- OS: Arch Linux x86_64
- Kernel: 5.4.15-arch1

**Comment by RemixDev** [comment]
Already fixed in latest development branch commit

**Comment by tbartlett17** [comment]
I have built and ran the latest development build 4.3.1 and am still having the same issue.

####Desktop:
-OS: Arch Linux x86_64
-Kernel: 5.4.15-arch1

**Comment by RemixDev** [comment]
Did you delete the folder before re downloading?

**Comment by tbartlett17** [comment]
I cloned the development branch into a new project folder. Do you want me to try removing both versions and re download the development branch?

**Comment by RemixDev** [comment]
I mean the download folder, whee the tracks are saved

**Comment by tbartlett17** [comment]
I deleted the albums with incomplete tracks before attempting to re download them

**Comment by RemixDev** [comment]
And the app says that the download is completed with no errors?

**Comment by RemixDev** [comment]
Could you send me a logfile?
If you don't know where to find it check on the FAQs

**Comment by tbartlett17** [comment]
It says 5/5 0 Failed on the downloads page in the program. I will upload a log here shortly for you.

**Comment by tbartlett17** [comment]
This is the logfile for when i tried to download an album called SYZGYZ01 by Opiuo. The track  05 - Dalmations.flac was only partially downloaded. 

[2020-02-01-09.32.15.txt](https://github.com/RemixDev/DRemixIssues/files/4142987/2020-02-01-09.32.15.txt)

**Comment by RemixDev** [comment]
ECONNRESET
Seems like your connection is unstable

But it should report that as failed, and it doesn't
I'll try to fix that one

**Comment by tbartlett17** [comment]
hmm alright. I have been having some issues with the network at my home the past few days so that must be the cause then. I made a hotspot from my phone and re downloaded the album and didn't get the ECONNRESET error this time.
